#!/bin/bash
# nosqlbench/nosqlbench-build-docs
export GITHUB_TARGET_REPO_ORG=${GITHUB_TARGET_REPO_ORG:?GITHUB_TARGET_REPO_ORG must be set}
export GITHUB_TARGET_REPO_NAME=${GITHUB_TARGET_REPO_NAME:?GITHUB_TARGET_REPO_NAME must be set}

export GITHUB_TARGET_AUTHUSER=${GITHUB_TARGET_AUTHUSER:?GITHUB_TARGET_AUTHUSER must be set}
export GITHUB_TARGET_AUTHTOKEN=${GITHUB_TARGET_AUTHTOKEN:?GITHUB_TARGET_AUTHTOKEN must be set}


git clone https://${GITHUB_TARGET_AUTHUSER}:${GITHUB_TARGET_AUTHTOKEN}@github.com/${GITHUB_TARGET_REPO_ORG}/${GITHUB_TARGET_REP_NAME}.git ${GITHUB_TARGET_REPO_NAME}
cd ${GITHUB_TARGET_REP_NAME}
echo "files listing"
find .
git remote set-url origin https://${GITHUB_TARGET_AUTHUSER}:${GITHUB_TARGET_AUTHTOKEN}@github.com/${GITHUB_TARGET_REPO_ORG}/${GITHUB_TARGET_REP_NAME}.git
git remote -v
rsync -av --delete 

