on:
  push:
    branches:
      - main 
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Build and Deploy Static Site'
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: ./site
          TOKEN: ${{ secrets.TOKEN }}
